name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Create env file
        run: |
          touch .env
          echo VITE_SERVER_URL=${{ secrets.VITE_SERVER_URL }} >> .env
          cat .env

      - name: Install dependancies
        run: yarn

      - name: Build project
        run: yarn build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
